---
title: 'The Role of Emotion in Learning Trustworthiness from Eye-gaze: Evidence from Facial Electromyography'
author: "Abraham Alex"
output: 
  html_document:
    toc: false
    toc_float: false

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


# Paper Summary

1.	Luis et al. conducted a study to determine how particular implicit emotions are elicited in response to the congruency of gaze-cues and how these emotions can impact the perception of trustworthiness. The somatic marker hypothesis posits that emotional reactions play a role in influencing the decision making process. As a result, it was hypothesized that emotional responses, elicited by congruent or incongruent gaze-cues, affect perceptions of trustworthiness. Electromyography (EMG) was used to gauge emotional responses. EMG is a technique that attempts to quantify the activity of particular facial muscles in order to make connections between the muscle activity and embodied emotional reactions. For instance, the corrugator facial muscle, the muscle involved in frowning, is used to convey emotions of anger and distress while the zygomaticus facial muscle, the muscle involved in smiling, is associated with positive emotions. The EMG activity was assumed be significantly different between subjects that report either high or low trust ratings. Participant response time and trust ratings were also collected to investigate the possible connection between embodied emotional reactions and trustworthiness.
	
	Experiment 1 sought to determine the emotional reactions that arose from observed gaze-cues and how such emotions ultimately affected trust ratings. The experiment consisted of 50 participants who were presented with images of either a male or a female. During the course of this experiment, EMG electrodes were attached to the general areas corresponding to the corrugator and zygomaticus facial muscles. A ground electrode was attached to the forehead to create the spurious impression that the instrument was reading frontal lobe activity rather than facial expressions. In the trustworthiness rating phase, the participants were presented with a fixation cross for 1000 ms, then a straightforward looking face for 1000 ms, and lastly a question asking for the trustworthiness rating of the individual in the picture with answers ranging from “very untrustworthy” to “very trustworthy.” The trustworthiness rating phase established baseline ratings such that the ratings by validity (congruent or incongruent) for a certain gender were relatively similar. In the gaze-cueing phase, the participants were presented with a fixation cross for 1500 ms and then a straightforward looking face for 1500 ms. A sideways looking face, a face directed forward with the eyes oriented to either side, was presented on the screen for 500 ms. Then, an object was randomly positioned at either side of the picture, such that the pictured face was either looking at the object (congruent condition) or away from the object (incongruent condition). The participants were instructed to identify the object as a garage object or a household object as quickly and accurately as possible within 5 seconds in order to draw conscious attention away from the pictured individuals. In fact, the participants were initially told that the faces were irrelevant to the task. After either a choice was made or 5 seconds had elapsed, the object disappeared and the pictured face gazed forward for 2000 ms. Lastly, the participants were presented with a screen with the words “Please Relax” for 4000 ms. Following this process, the participants were asked to rate the trustworthiness of the face from “very untrustworthy” to “very trustworthy.” The computer translated the ratings into numbers ranging from -100 to 100 for very untrustworthy to very trustworthy, respectively. The electrodes were then removed and the participants were debriefed.
	
	Experiment 2 used arrow-cues with various patterns, instead of faces, to evaluate the likeness rating to congruent and incongruent arrows. The experiment consisted of 31 subjects presented with distinctly patterned arrows. The design of this experiment was very similar to that of experiment 1. In the gaze-cueing phase, the participants were presented with a fixation cross for 1500 ms and then a neutral arrow, an arrow pointing neither to the left nor right, for 1500 ms. Then, an arrow oriented to either side was presented on the screen for 500 ms. An object was randomly positioned at either side of the picture, such that the arrow was either facing the object (congruent condition) or away from the object (incongruent condition). The participants were instructed to identify the object as a garage object or a household object quickly and accurately as possible within 5 seconds. After either a choice was made or 5 seconds had elapsed, the object disappeared and the neutral arrow was shown again for 2000 ms. Lastly, the participants were presented with a screen with the words “Please Relax” for 4000 ms. Following this process, the participants were asked to rate the liking of the arrow from “dislike very much” to “like very much.” The electrodes were then removed and the participants were debriefed.
	
	The results show that the participants were slower to identify the object for incongruent condition than congruent condition and that incongruent faces were rated as less trustworthy compared to that of congruent faces. The embodied emotional reaction was measured using EMG to determine how such reactions played a role in trust ratings. The EMG patterns for participants viewing the congruent faces were distinct from that of participants viewing incongruent faces, suggesting an unconscious bias against incongruent gaze-cues. By comparing the trust ratings with the EMG readings, Luis et al. confirmed the hypothesis that embodied emotional response affect the trust perception of gaze-cues. Experiment 2 gave further credence to this hypothesis. The second experiment demonstrated that trust ratings of experiment 1 were impacted by the particular characteristics of the presented face and eye-gaze. Unlike faces, arrows cannot effectively evoke emotions and learning, suggesting that the emotional reactions to faces played a significant role in determining trustworthiness in experiment 1.
